/* Schemas */

IF SCHEMA_ID('udfs') IS NULL
  EXECUTE('CREATE SCHEMA udfs')

IF SCHEMA_ID('ref') IS NULL
  EXECUTE('CREATE SCHEMA ref')

IF SCHEMA_ID('views') IS NULL
  EXECUTE('CREATE SCHEMA views')
  
IF SCHEMA_ID('usps') IS NULL
  EXECUTE('CREATE SCHEMA usps')

GO